<?php

// konfigurasi utk label service / layanan
return [
	'xl'		=> 'XL',
	'telkomsel'	=> 'Tekomsel',
	'indosat'	=> 'Indosat',
	'smartfren'	=> 'Smartfren',
	'tri'		=> 'Three',
	'axis'		=> 'Axis',

	'pgn'		=> 'PGM',
	'pln'		=> 'PLN',
	'telkom'	=> 'Telkom',

	'flight'	=> '',
	'train'		=> '',
	'movie'		=> '',
	'hotel'		=> '',

	'bpjs_kesehatan'	=> 'BPJS Kesehatan',
	'bpjs_tenagakerja'	=> 'BPJS Tenaga Kerja',
	'jiwasraya'			=> 'Asuransi Jiwa Sraya',
	'prudentials'		=> 'Asuransi Prudentials',
	'sinarmaslife'		=> 'Asuransi Sinar Mas Life',
	'sinarmas'			=> 'Asuransi Sinar Mas',
	'aia'				=>	'Asuransi AIA',

	'emoney'	=> 'EMONEY',
	'ecash'		=> 'ECASH',
	'ovo'		=> 'OVO',
	'gopay'		=> 'GOPAY',
	'dana'		=> 'DANA',
	'mtix'		=> 'TIX-iD',
	'tixid'		=> 'M-TIX',

	'centrinnet'	=> '',
	'indihome'		=> 'Indihome',
	'speedy'		=> 'Speedy',
	'firstmedia'	=> 'First Media',
	'okevision'		=> 'Okevision',
	'telkom'		=> 'Telkom',
	'cbn'			=> '',

	'zynga'			=> '',
	'winner'		=> '',
	'wavepro'		=> '',
	'vtc'			=> '',
	'unipin'		=> '',
	'teracord'		=> '',
	'serenity'		=> '',
	'rappelzon'		=> '',
	'playspan'		=> '',
	'playpoint'		=> '',
	'playon'		=> '',
	'orangegame'	=> '',
	'mycard'		=> '',
	'mol'			=> '',
	'mobilelegends'	=> 'Mobile Legends',
	'megaxus'		=> 'Megaxus',
	'matchmove'		=> '',
	'mainkan'		=> '',
	'lyto'			=> 'Lyto',
	'koram'			=> '',
	'itunes'		=> 'iTunes',
	'ingame'		=> '',
	'iahgames'		=> '',
	'googleplay'	=> 'Google Play',
	'golonline'		=> '',
	'gogame'		=> '',
	'gemscool'		=> 'Gemscool',
	'garena'		=> 'Garena',
	'fastblack'		=> '',
	'digicash'		=> '',;
	'dasagame'		=> '',
	'cherry'		=> '',
	'cabal'			=> '',
	'asiasoft'		=> '',

	'wom'			=> 'WOM Multifinance',
	'baf'			=> 'Bussan Auto Finance',
	'maf'			=> 'Mega Auto Finance',
	'mcf'			=> 'Mega Central Finance',
	'clmb'			=> 'Columbia Finance',
	'woka'			=> 'WOKA Finance',
	'smart'			=> 'Smart Finance',
	'adira'			=> 'Adira Finance',
	'fif'			=> 'FIF Finance',
	'anz'			=> 'ANZ Personal Loan',
	'ktapermata'	=> 'KTA Permata',
	'citibankcash'	=> 'Citibank Ready Cash',
	'citibankpay'	=> 'Citibank Personal Loan',

	'americaexp'	=> 'American Express',
	'bni'			=> 'Bank BNI',
	'uob'			=> 'Bank UOB',
	'anz'			=> 'Bank ANZ',
	'permata'		=> 'Bank Permata',
	'danamon'		=> 'Bank Danamon',
	'panin'			=> 'Bank Panin',
	'bukopin'		=> 'Bank Bukopin',
	'bumiputra'		=> 'Bank Bumi Putera',
	'citibank'		=> 'Citibank',
	'digibank'		=> 'Digibank',
];