Bali
	KAB BADUNG (BALI)
	KAB BULELENG (BALI)
	KAB KLUNGKUNG
	KOTA DENPASAR (BALI)
DI Yogyakarta
	KAB KULON PROGO
	KAB SLEMAN DIY
DKI Jakarta
	AETRA JAKARTA
	PALYJA JAKARTA
Jawa Barat
	KAB INDRAMAYU
	KOTA SUKABUMI
	KOTA BEKASI (TIRTA PATRIOT)
	KAB BANDUNG (JABAR)
	KAB BANDUNG BARAT
	KAB BOGOR (JABAR)
	KAB CIAMIS
	KAB CIANJUR
	KAB GARUT
	KAB KARAWANG
	KAB SERANG
	KAB SUMEDANG
	KAB SUBANG
	KAB TASIKMALAYA
	KOTA BANDUNG (JABAR)
	KOTA BANJAR
	KOTA BOGOR (JABAR)
	KOTA CIREBON
	KOTA DEPOK (JABAR)
Jawa Tengah
	KAB BATANG
	KAB TEGAL
	KAB BANYUMAS (JATENG)
	KAB BLORA
	KAB BOYOLALI (JATENG)
	KAB BREBES (JATENG)
	KAB CILACAP (JATENG)
	KAB GROBOGAN (JATENG)
	KAB JEPARA
	KAB KARANGANYAR (JATENG)
	KAB KEBUMEN (JATENG)
	KAB KENDAL (JATENG)
	KAB KLATEN (JATENG)
	KAB MAGELANG
	KAB KUDUS
	KAB PATI
	KAB PEKALONGAN (JATENG)
	KAB PURBALINGGA (JATENG)
	KAB PURWOREJO (JATENG)
	KAB REMBANG (JATENG)
	KAB SEMARANG (JATENG)
	KAB SURAKARTA
	KAB TEMANGGUNG
	KAB SRAGEN (JATENG)
	KAB SUKOHARJO
	KAB WONOGIRI (JATENG)
	KAB WONOSOBO (JATENG)
	KOTA BATANG (JATENG)
	KOTA MAGELANG
	KOTA SALATIGA
	KOTA SEMARANG (TIRTA MOEDAL)
	KOTA SOLO
	KOTA TEGAL
Jawa Timur
	KAB BANGKALAN (JATIM)
	KAB BANYUWANGI
	KAB BLITAR
	KAB BOJONEGORO (JATIM)
	KAB BONDOWOSO (JATIM)
	KAB GRESIK
	KAB JEMBER (JATIM)
	KAB JOMBANG
	KAB LAMONGAN
	KAB LUMAJANG (JATIM)
	KAB MAGETAN
	KAB MALANG (JATIM)
	KAB MOJOKERTO (JATIM)
	KAB PONOROGO
	KAB NGANJUK
	KAB NGAWI
	KAB PROBOLINGGO (JATIM)
	KAB TUBAN
	KAB SIDOARJO (JATIM)
	KAB SITUBONDO
	KAB TULUNGAGUNG
	KOTA MADIUN (JATIM)
	KOTA MALANG
	KOTA MOJOKERTO
	KOTA PASURUAN (JATIM)
	KOTA PROBOLINGGO
	KOTA SURABAYA
Kalimantan
	INTAN BANJAR
	KAB BALANGAN (KALSEL)
	KAB TAPIN (KALSEL)
	KOTA BALIKPAPAN (KALTIM)
	KOTA BANJARMASIN
	KOTA TANAH GROGOT (KALTIM)
Kalimantan Barat
	KOTA PONTIANAK
Kalimantan Selatan
	KAB BARABAI (KALSEL)
Kalimantan Tengah
	PANGKALAN BUN (KOTAWARINGIN BARAT)
Kalimantan Timur
	KAB PASER
	KAB SAMARINDA
	KOTA SAMARINDA
Kepulauan Riau
	ATB BATAM
Nusa Tenggara Barat (NTB)
	KAB LOMBOK TENGAH (NTB)
	KOTA MATARAM
Nusa Tenggara Timur (NTT)
	KAB KUPANG
	KOTA KUPANG
Sulawesi
	KAB BONE
	KAB DONGGALA
	KAB GOWA
	KAB MAROS
	KAB POLEWALI MANDAR
	KAB TAKALAR
	KOTA MAKASSAR (SULSEL)
	KOTA MANADO (SULUT)
	KOTA PALOPO
Sumatera
	ACEH BARAT
	ACEH BESAR
	ACEH TIMUR
	KAB PIDIE
	KOTA BANDA ACEH
	KOTA BANDAR LAMPUNG
	KOTA MEDAN (SUMUT)
	KOTA PADANG
	KOTA PALEMBANG (SUMSEL)
Sumatera Barat
	KAB PASAMAN