<?php

// konfigurasi utk memilih vendor yg diminta
return [
	'flight' => 'pulsamu',
	'train' => 'pulsamu',
	'movie' => 'pulsamu',
	'hotel' => 'pulsamu',
	'pulsa_pra' => [
		'xl'		=> 'pulsamu',
		'telkomsel'	=> 'pulsamu',
		'indosat'	=> 'pulsamu',
		'smartfren'	=> 'pulsamu',
		'tri'		=> 'pulsamu',
		'axis'		=> 'pulsamu',
	],
	'data_pra' => [
		'xl'		=> 'pulsamu',
		'telkomsel'	=> 'pulsamu',
		'indosat'	=> 'pulsamu',
		'smartfren'	=> 'pulsamu',
		'tri'		=> 'pulsamu',
		'axis'		=> 'pulsamu',
	],
	'pulsa_pasca' => [
		'xl'		=> 'pulsamu',
		'telkomsel'	=> 'pulsamu',
		'indosat'	=> 'pulsamu',
		'smartfren'	=> 'pulsamu',
		'tri'		=> 'pulsamu',
		'axis'		=> 'pulsamu',
	],
	'pln_pra' => 'pulsamu',
	'pln_pasca' => 'pulsamu',
	'pgn' => 'pulsamu',
	'telkom' => 'pulsamu',
	'pdam' => [
	],
	'internet_pasca' => [
		'indihome'		=> 'pulsamu',
		'speedy'		=> 'pulsamu'
		'firstmedia'	=> 'pulsamu'
		'okevision'		=> 'pulsamu'
		'cbn'			=> 'pulsamu'
		'centrinnet'	=> 'pulsamu'
	],
	'internet_pra' => [
		'wifi_id'	=> 'pulsamu',
	],
	'voucher_game' => [
		'zynga'			=> 'pulsamu',
		'winner'		=> 'pulsamu',
		'wavepro'		=> 'pulsamu',
		'vtc'			=> 'pulsamu',
		'unipin'		=> 'pulsamu',
		'teracord'		=> 'pulsamu',
		'serenity'		=> 'pulsamu',
		'rappelzon'		=> 'pulsamu',
		'playspan'		=> 'pulsamu',
		'playpoint'		=> 'pulsamu',
		'playon'		=> 'pulsamu',
		'orangegame'	=> 'pulsamu',
		'mycard'		=> 'pulsamu',
		'mol'			=> 'pulsamu',
		'mobilelegends'	=> 'pulsamu',
		'megaxus'		=> 'pulsamu',
		'matchmove'		=> 'pulsamu',
		'mainkan'		=> 'pulsamu',
		'lyto'			=> 'pulsamu',
		'koram'			=> 'pulsamu',
		'itunes'		=> 'pulsamu',
		'ingame'		=> 'pulsamu',
		'iahgames'		=> 'pulsamu',
		'googleplay'	=> 'pulsamu',
		'golonline'		=> 'pulsamu',
		'gogame'		=> 'pulsamu',
		'gemscool'		=> 'pulsamu',
		'garena'		=> 'pulsamu',
		'fastblack'		=> 'pulsamu',
		'digicash'		=> 'pulsamu',;
		'dasagame'		=> 'pulsamu',
		'cherry'		=> 'pulsamu',
		'cabal'			=> 'pulsamu',
		'asiasoft'		=> 'pulsamu',
	],
	'asuransi' => [
		'bpjs_kesehatan'	=> 'pulsamu',
		'bpjs_tenagakerja'	=> 'pulsamu',
		'jiwasraya'			=> 'pulsamu',
		'prudentials'		=> 'pulsamu',
		'sinarmaslife'		=> 'pulsamu',
		'sinarmas'			=> 'pulsamu',
		'aia'				=>	'',
	],
	'finance' => [
		'wom'			=> 'pulsamu',
		'baf'			=> 'pulsamu',
		'maf'			=> 'pulsamu',
		'mcf'			=> 'pulsamu',
		'clmb'			=> 'pulsamu',
		'woka'			=> 'pulsamu',
		'smart'			=> 'pulsamu',
		'adira'			=> 'pulsamu',
		'fif'			=> 'pulsamu',
		'anz'			=> 'pulsamu',
		'ktapermata'	=> 'pulsamu',
		'citibankcash'	=> 'pulsamu',
		'citibankpay'	=> 'pulsamu',
	],
	'epayment' => [
		'emoney'	=> 'pulsamu',
		'ecash'		=> 'pulsamu',
		'ovo'		=> 'pulsamu',
		'gopay'		=> 'pulsamu',
		'dana'		=> 'pulsamu',
		'mtix'		=> 'pulsamu',
		'tixid'		=> 'pulsamu',
	],
	'kartu_kredit' => [
		'americaexp'	=> 'pulsamu',
		'bni'			=> 'pulsamu',
		'uob'			=> 'pulsamu',
		'anz'			=> 'pulsamu',
		'permata'		=> 'pulsamu',
		'danamon'		=> 'pulsamu',
		'panin'			=> 'pulsamu',
		'bukopin'		=> 'pulsamu',
		'bumiputra'		=> 'pulsamu',
		'citibank'		=> 'pulsamu',
	]
];